"""
Session checkpoint and restore — S3-based persistence.

Part of: app.platform (infrastructure layer)

Saves executor state (namespace + local files) to S3 on termination,
and restores them when launching a new MicroVM from a session checkpoint.
Includes per-step timing for performance analysis.

S3 structure:
  sessions/{session_id}/checkpoint.pkl   — dill-serialized namespace
  sessions/{session_id}/files.tar.gz     — /tmp/ data files
  sessions/{session_id}/requirements.txt — runtime-installed packages
  sessions/{session_id}/metadata.json    — session info
"""

import os
import io
import tarfile
import glob
import json
import subprocess
import logging
from datetime import datetime, timezone

logger = logging.getLogger(__name__)

# Types excluded from checkpoint serialization.
# These are transient display/rendering objects that:
# 1. Are extremely expensive to serialize (dominate checkpoint time)
# 2. Cannot be meaningfully restored (they reference closed backends/canvases)
# 3. Are already rendered as images in the frontend cell output
# 4. Can be regenerated by re-running the visualization cell (data is preserved)
#
# Impact: After rotation, variables like `fig`, `ax`, `plt` won't exist in the
# namespace. The user's DataFrames and computed values survive. Charts are still
# visible in cell output. Re-running a plot cell regenerates the figure object.
_EXCLUDED_TYPE_NAMES = frozenset({
    # Matplotlib
    "Figure",
    "Axes",
    "AxesSubplot",
    "Subplot",
    "FigureCanvasAgg",
    "FigureCanvasPdf",
    "FigureCanvasSVG",
    # PIL/Pillow images (specific file-type classes)
    "PngImageFile",
    "JpegImageFile",
    "GifImageFile",
    "BmpImageFile",
    "TiffImageFile",
    "WebPImageFile",
})

# Module prefixes — any object from these modules is excluded
_EXCLUDED_MODULE_PREFIXES = (
    "matplotlib.",
    "PIL.",
)


def _is_excluded_from_checkpoint(value) -> bool:
    """
    Check if a value should be excluded from checkpoint serialization.
    Returns True for transient display objects (matplotlib figures, PIL images, etc.)
    that are expensive to serialize and not essential for state continuity.
    """
    type_name = type(value).__name__
    module = getattr(type(value), "__module__", "") or ""

    # Fast check: type name
    if type_name in _EXCLUDED_TYPE_NAMES:
        return True

    # Module-based check: anything from matplotlib.* or PIL.*
    if module.startswith(_EXCLUDED_MODULE_PREFIXES):
        return True

    return False


class CheckpointManager:
    """
    Manages S3 checkpoint/restore for a MicroVM session.

    Holds references to the executor and session_state so they don't
    need to be passed to every method call.
    """

    def __init__(self, executor, session_state: dict, *, skip_display_objects: bool = True):
        self._executor = executor
        self._session_state = session_state
        self._bucket: str | None = None
        self._skip_display_objects = skip_display_objects
        self._user_installed_packages: list[str] = []  # Packages installed via /install endpoint
        self.last_save_timings: dict = {}
        self.last_restore_timings: dict = {}
        self.last_checkpoint_at: float = 0  # Unix timestamp of last successful save

    def record_package_install(self, package: str):
        """Track a user-installed package (called by /install endpoint on success)."""
        if package and package not in self._user_installed_packages:
            self._user_installed_packages.append(package)
            logger.info(f"   Recorded user package install: {package} (total: {len(self._user_installed_packages)})")

    @property
    def bucket(self) -> str:
        """Get the S3 bucket name (from session config or constructed from account)."""
        if self._bucket:
            return self._bucket

        # Use bucket name passed from the proxy via runHookPayload
        if self._session_state.get("artifacts_bucket"):
            self._bucket = self._session_state["artifacts_bucket"]
            return self._bucket

        # Fallback: construct from account ID + region
        import boto3
        region = os.environ.get("AWS_REGION", "us-west-2")
        sts = boto3.client("sts")
        account_id = sts.get_caller_identity()["Account"]
        self._bucket = f"microvm-sandbox-artifacts-{account_id}-{region}"
        return self._bucket

    def save(self, session_id: str):
        """
        Checkpoint current state to S3.
        Called from the /terminate lifecycle hook.
        """
        import boto3
        import dill
        import time as _time

        s3 = boto3.client("s3")
        prefix = f"sessions/{session_id}"
        step_timings = {}

        # 1. Serialize the executor namespace
        # Strategy: try bulk serialize first (fast). If it fails (some object can't be
        # pickled, like _csv.writer or database connections), fall back to per-variable
        # testing to identify and skip only the problematic ones.
        # Always exclude: modules (can be re-imported) and __dunder__ keys.
        import types as _types
        import traceback as _tb
        t0 = _time.perf_counter()

        # Log what's in the namespace
        all_keys = [k for k in self._executor._namespace.keys() if not (k.startswith("__") and k.endswith("__"))]
        logger.info(f"   Serializing namespace... ({len(all_keys)} keys: {all_keys[:20]})")

        # Separate modules from data
        modules_skipped = []
        display_skipped = []
        namespace_to_save = {}
        for key, value in self._executor._namespace.items():
            if key.startswith("__") and key.endswith("__"):
                continue
            if isinstance(value, _types.ModuleType):
                modules_skipped.append(key)
                continue
            if self._skip_display_objects and _is_excluded_from_checkpoint(value):
                display_skipped.append(f"{key}({type(value).__name__})")
                continue
            namespace_to_save[key] = value

        if modules_skipped:
            logger.info(f"   Skipped modules: {modules_skipped}")
        if display_skipped:
            logger.info(f"   Skipped display objects: {display_skipped}")
        logger.info(f"   To serialize: {len(namespace_to_save)} vars — {list(namespace_to_save.keys())[:20]}")

        try:
            checkpoint_bytes = dill.dumps(namespace_to_save)
            logger.info(f"   Bulk serialize OK: {len(checkpoint_bytes)} bytes")
        except Exception as bulk_err:
            logger.warning(f"   Bulk serialize FAILED: {bulk_err}")
            logger.warning(f"   Traceback: {_tb.format_exc()}")
            # Per-variable fallback
            safe_namespace = {}
            skipped_vars = []
            for key, value in namespace_to_save.items():
                try:
                    dill.dumps(value)
                    safe_namespace[key] = value
                except Exception as var_err:
                    skipped_vars.append(f"{key}({type(value).__name__}): {var_err}")
                    logger.warning(f"   Skipping: {key} ({type(value).__name__}): {var_err}")
            logger.info(f"   Per-var result: {len(safe_namespace)} saved, {len(skipped_vars)} skipped")
            if skipped_vars:
                logger.info(f"   Skipped details: {skipped_vars}")
            namespace_to_save = safe_namespace
            try:
                checkpoint_bytes = dill.dumps(namespace_to_save)
                logger.info(f"   Fallback serialize OK: {len(checkpoint_bytes)} bytes")
            except Exception as fallback_err:
                logger.error(f"   Fallback serialize also FAILED: {fallback_err}")
                raise RuntimeError(f"Cannot serialize namespace: {fallback_err}") from fallback_err

        step_timings["serialize"] = _time.perf_counter() - t0

        # 2. Upload checkpoint.pkl to S3
        t0 = _time.perf_counter()
        s3.put_object(Bucket=self.bucket, Key=f"{prefix}/checkpoint.pkl", Body=checkpoint_bytes)
        step_timings["upload_pkl"] = _time.perf_counter() - t0
        logger.info(f"   Namespace: {len(namespace_to_save)} vars, {len(checkpoint_bytes) / 1024:.1f} KB (serialize: {step_timings['serialize']*1000:.0f}ms, upload: {step_timings['upload_pkl']*1000:.0f}ms)")

        # 2b. Archive local data files from /tmp/
        t0 = _time.perf_counter()
        logger.info("   Archiving local files...")
        data_extensions = ['*.csv', '*.xlsx', '*.xls', '*.parquet', '*.json', '*.txt']
        data_files = []
        for ext in data_extensions:
            data_files.extend(glob.glob(f'/tmp/{ext}'))

        if data_files:
            tar_buffer = io.BytesIO()
            with tarfile.open(fileobj=tar_buffer, mode='w:gz') as tar:
                for filepath in data_files:
                    tar.add(filepath, arcname=os.path.basename(filepath))
            tar_buffer.seek(0)
            s3.put_object(Bucket=self.bucket, Key=f"{prefix}/files.tar.gz", Body=tar_buffer.read())
            step_timings["archive_files"] = _time.perf_counter() - t0
            logger.info(f"   Files: {len(data_files)} archived ({step_timings['archive_files']*1000:.0f}ms)")
        else:
            step_timings["archive_files"] = _time.perf_counter() - t0

        # 3. Save user-installed packages (just the list — no pip freeze needed)
        t0 = _time.perf_counter()
        if self._user_installed_packages:
            packages_content = '\n'.join(self._user_installed_packages)
            s3.put_object(Bucket=self.bucket, Key=f"{prefix}/requirements.txt", Body=packages_content)
            logger.info(f"   Packages: {len(self._user_installed_packages)} user-installed saved")
        else:
            logger.info("   Packages: none installed by user (skipping)")
        step_timings["packages"] = _time.perf_counter() - t0

        # 4. Save metadata (includes timing breakdown for analysis)
        t0 = _time.perf_counter()
        metadata = {
            "session_id": session_id,
            "microvm_id": self._session_state.get("microvm_id"),
            "checkpointed_at": datetime.now(timezone.utc).isoformat(),
            "execution_count": self._executor.get_stats()["execution_count"],
            "variables_count": len(namespace_to_save),
            "files_count": len(data_files),
            "checkpoint_size_kb": round(len(checkpoint_bytes) / 1024, 1),
            "save_timings_ms": {k: round(v * 1000, 1) for k, v in step_timings.items()},
        }
        s3.put_object(
            Bucket=self.bucket,
            Key=f"{prefix}/metadata.json",
            Body=json.dumps(metadata, indent=2),
            ContentType="application/json",
        )
        step_timings["metadata"] = _time.perf_counter() - t0
        total_time = sum(step_timings.values())
        logger.info(f"   ✅ Checkpoint complete: s3://{self.bucket}/{prefix}/ ({total_time*1000:.0f}ms total)")
        logger.info(f"   ⏱  Breakdown: serialize={step_timings['serialize']*1000:.0f}ms, upload_pkl={step_timings['upload_pkl']*1000:.0f}ms, archive={step_timings['archive_files']*1000:.0f}ms, packages={step_timings['packages']*1000:.0f}ms, metadata={step_timings['metadata']*1000:.0f}ms")
        self.last_save_timings = {k: round(v * 1000, 1) for k, v in step_timings.items()}
        self.last_save_timings["total_ms"] = round(total_time * 1000, 1)
        self.last_checkpoint_at = _time.time()

    def restore(self, session_id: str):
        """
        Restore executor state from a previous S3 checkpoint.
        Called from the /run lifecycle hook when restoreFromSession is set.
        """
        import boto3
        import dill
        import time as _time

        s3 = boto3.client("s3")
        prefix = f"sessions/{session_id}"
        step_timings = {}

        # 1. Restore namespace
        try:
            t0 = _time.perf_counter()
            logger.info("   Restoring namespace...")
            resp = s3.get_object(Bucket=self.bucket, Key=f"{prefix}/checkpoint.pkl")
            pkl_bytes = resp["Body"].read()
            step_timings["download_pkl"] = _time.perf_counter() - t0

            t0 = _time.perf_counter()
            namespace = dill.loads(pkl_bytes)
            # Deep-copy mutable containers (lists, dicts) to break any dill internal
            # references that could prevent mutations from being captured on re-serialize.
            import copy
            for key, value in namespace.items():
                if isinstance(value, (list, dict, set)):
                    namespace[key] = copy.deepcopy(value)
            self._executor._namespace.update(namespace)
            step_timings["deserialize"] = _time.perf_counter() - t0
            logger.info(f"   Restored {len(namespace)} variables ({len(pkl_bytes)/1024:.1f} KB, download: {step_timings['download_pkl']*1000:.0f}ms, deserialize: {step_timings['deserialize']*1000:.0f}ms)")
        except Exception as e:
            logger.error(f"   Failed to restore namespace: {e}")

        # 2. Restore local files
        try:
            t0 = _time.perf_counter()
            logger.info("   Restoring files...")
            resp = s3.get_object(Bucket=self.bucket, Key=f"{prefix}/files.tar.gz")
            tar_buffer = io.BytesIO(resp["Body"].read())
            step_timings["download_files"] = _time.perf_counter() - t0

            t0 = _time.perf_counter()
            with tarfile.open(fileobj=tar_buffer, mode='r:gz') as tar:
                tar.extractall(path="/tmp/")
            step_timings["extract_files"] = _time.perf_counter() - t0
            logger.info(f"   Files restored to /tmp/ (download: {step_timings['download_files']*1000:.0f}ms, extract: {step_timings['extract_files']*1000:.0f}ms)")
        except s3.exceptions.NoSuchKey:
            logger.info("   No files archive found (skipping)")
            step_timings["download_files"] = 0
            step_timings["extract_files"] = 0
        except Exception as e:
            logger.error(f"   Failed to restore files: {e}")

        # 3. Install user-installed packages (simple list — no diffing needed)
        try:
            t0 = _time.perf_counter()
            resp = s3.get_object(Bucket=self.bucket, Key=f"{prefix}/requirements.txt")
            requirements = resp["Body"].read().decode("utf-8")
            if requirements.strip():
                import sys
                packages = [p.strip() for p in requirements.strip().split('\n') if p.strip()]
                if packages:
                    logger.info(f"   Installing {len(packages)} user packages: {', '.join(packages)}")
                    subprocess.run(
                        [sys.executable, "-m", "pip", "install", "--quiet"] + packages,
                        timeout=60
                    )
                    # Track them in our list for future checkpoints
                    self._user_installed_packages = packages
                    logger.info(f"   ✓ Installed {len(packages)} packages")
            step_timings["packages"] = _time.perf_counter() - t0
        except s3.exceptions.NoSuchKey:
            step_timings["packages"] = 0
        except Exception as e:
            logger.warning(f"   Package restore warning: {e}")
            step_timings["packages"] = _time.perf_counter() - t0 if 't0' in dir() else 0

        total_time = sum(step_timings.values())
        logger.info(f"   ✅ Session restored from: {session_id} ({total_time*1000:.0f}ms total)")
        logger.info(f"   ⏱  Breakdown: download_pkl={step_timings.get('download_pkl',0)*1000:.0f}ms, deserialize={step_timings.get('deserialize',0)*1000:.0f}ms, download_files={step_timings.get('download_files',0)*1000:.0f}ms, extract={step_timings.get('extract_files',0)*1000:.0f}ms, packages={step_timings.get('packages',0)*1000:.0f}ms")
        self.last_restore_timings = {k: round(v * 1000, 1) for k, v in step_timings.items()}
        self.last_restore_timings["total_ms"] = round(total_time * 1000, 1)
